/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_remotedroid_universal_natives_FrameHandlerU */

#ifndef _Included_com_example_remotedroid_universal_natives_FrameHandlerU
#define _Included_com_example_remotedroid_universal_natives_FrameHandlerU
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_remotedroid_universal_natives_FrameHandlerU_BYTE_PER_PIXEL
#define com_example_remotedroid_universal_natives_FrameHandlerU_BYTE_PER_PIXEL 4L
#ifdef __cplusplus
}
#endif
#endif
